import "server-only";

export type GitHubFile = { path: string; content: string };

function cleanRepoPath(path: string) {
  return path
    .replace(/^\/+/, "")
    .replace(/\\/g, "/")
    .split("/")
    .filter(Boolean)
    .map((part) => encodeURIComponent(part))
    .join("/");
}

async function githubJson(url: string, init: RequestInit) {
  const response = await fetch(url, { ...init, cache: "no-store" });
  const text = await response.text();
  const json = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : null;
  if (!response.ok) {
    const message = typeof json === "object" && json && "message" in json ? String((json as any).message) : text;
    throw new Error(message || `GitHub request failed: ${response.status}`);
  }
  return json;
}

export async function createArtifactPullRequest({
  title,
  files,
  branchPrefix = "hyperspeed",
}: {
  title: string;
  files: GitHubFile[];
  branchPrefix?: string;
}) {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  const repo = process.env.GITHUB_REPOSITORY;
  const defaultBranch = process.env.GITHUB_DEFAULT_BRANCH || "main";
  if (!token || !repo) {
    return {
      ok: false as const,
      reason: "Set GITHUB_TOKEN and GITHUB_REPOSITORY to enable real PR creation.",
    };
  }

  const [owner, name] = repo.split("/");
  if (!owner || !name) return { ok: false as const, reason: "GITHUB_REPOSITORY must be owner/repo." };

  const cleanFiles = files
    .map((file) => ({ path: file.path.replace(/^\/+/, "").trim(), content: file.content ?? "" }))
    .filter((file) => file.path && !file.path.endsWith(".gitkeep"));

  if (!cleanFiles.length) return { ok: false as const, reason: "No artifact files available for PR creation." };

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json",
  };
  const api = `https://api.github.com/repos/${owner}/${name}`;
  const branch = `${branchPrefix}/${Date.now()}`;
  let branchCreated = false;

  try {
    const baseRef = await githubJson(`${api}/git/ref/heads/${defaultBranch}`, { headers });
    const baseSha = baseRef?.object?.sha;
    if (!baseSha) return { ok: false as const, reason: "Could not resolve default branch SHA." };

    await githubJson(`${api}/git/refs`, {
      method: "POST",
      headers,
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
    });
    branchCreated = true;

    for (const file of cleanFiles) {
      const encodedPath = cleanRepoPath(file.path);
      const currentRes = await fetch(`${api}/contents/${encodedPath}?ref=${branch}`, {
        headers,
        cache: "no-store",
      });
      const current = currentRes.ok ? await currentRes.json() : null;
      const body: Record<string, unknown> = {
        message: `Update ${file.path} from HyperSpeed`,
        content: Buffer.from(file.content, "utf8").toString("base64"),
        branch,
      };
      if (current?.sha) body.sha = current.sha;

      await githubJson(`${api}/contents/${encodedPath}`, {
        method: "PUT",
        headers,
        body: JSON.stringify(body),
      });
    }

    const pr = await githubJson(`${api}/pulls`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        title: title || "HyperSpeed generated app update",
        head: branch,
        base: defaultBranch,
        body: [
          "Generated by HyperSpeed.",
          "",
          `Files changed: ${cleanFiles.length}`,
          "Review the artifact files before merging.",
        ].join("\n"),
        maintainer_can_modify: true,
      }),
    });

    return { ok: true as const, url: pr.html_url as string, branch, number: pr.number as number };
  } catch (error) {
    // A partially-committed branch with no PR is dead weight and clutters the
    // remote on every retry — clean it up before surfacing the failure.
    if (branchCreated) {
      try {
        await githubJson(`${api}/git/refs/heads/${encodeURIComponent(branch)}`, { method: "DELETE", headers });
      } catch {
        // best-effort cleanup; the original error is what the caller needs
      }
    }
    return { ok: false as const, reason: error instanceof Error ? error.message : "GitHub PR creation failed." };
  }
}
