import "server-only";

export type GitHubFile = { path: string; content: string };

export async function createArtifactPullRequest({
  title,
  files,
  branchPrefix = "hyperspeed",
}: {
  title: string;
  files: GitHubFile[];
  branchPrefix?: string;
}) {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  const repo = process.env.GITHUB_REPOSITORY;
  const defaultBranch = process.env.GITHUB_DEFAULT_BRANCH || "main";
  if (!token || !repo) {
    return {
      ok: false as const,
      reason: "Set GITHUB_TOKEN and GITHUB_REPOSITORY to enable real PR creation.",
    };
  }

  const [owner, name] = repo.split("/");
  if (!owner || !name) return { ok: false as const, reason: "GITHUB_REPOSITORY must be owner/repo." };

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json",
  };
  const api = `https://api.github.com/repos/${owner}/${name}`;
  const branch = `${branchPrefix}/${Date.now()}`;

  const baseRefRes = await fetch(`${api}/git/ref/heads/${defaultBranch}`, { headers, cache: "no-store" });
  if (!baseRefRes.ok) return { ok: false as const, reason: await baseRefRes.text() };
  const baseRef = await baseRefRes.json();
  const baseSha = baseRef?.object?.sha;
  if (!baseSha) return { ok: false as const, reason: "Could not resolve default branch SHA." };

  const createRefRes = await fetch(`${api}/git/refs`, {
    method: "POST",
    headers,
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
  });
  if (!createRefRes.ok) return { ok: false as const, reason: await createRefRes.text() };

  for (const file of files.filter((item) => item.path && item.content !== undefined)) {
    const path = file.path.replace(/^\/+/, "");
    const currentRes = await fetch(`${api}/contents/${encodeURIComponent(path)}?ref=${branch}`, {
      headers,
      cache: "no-store",
    });
    const current = currentRes.ok ? await currentRes.json() : null;
    const body: Record<string, unknown> = {
      message: `Update ${path} from HyperSpeed`,
      content: Buffer.from(file.content, "utf8").toString("base64"),
      branch,
    };
    if (current?.sha) body.sha = current.sha;

    const writeRes = await fetch(`${api}/contents/${encodeURIComponent(path)}`, {
      method: "PUT",
      headers,
      body: JSON.stringify(body),
    });
    if (!writeRes.ok) return { ok: false as const, reason: await writeRes.text() };
  }

  const prRes = await fetch(`${api}/pulls`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      title: title || "HyperSpeed generated app update",
      head: branch,
      base: defaultBranch,
      body: "Generated by HyperSpeed. Review the artifact files before merging.",
    }),
  });
  if (!prRes.ok) return { ok: false as const, reason: await prRes.text() };
  const pr = await prRes.json();
  return { ok: true as const, url: pr.html_url as string, branch, number: pr.number as number };
}
